version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  user-service:
    build:
      context: ./user-service
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: users_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

  order-service:
    build:
      context: ./order-service
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: orders_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  product-service:
    build:
      context: ./product-service
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: products_db
    depends_on:
      - db
    ports:
      - "6000:6000"

volumes:
  pgdata:
