# docker-compose.yml
version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres-users

  product-service:
    build:
      context: ./product-service
    ports:
      - "5000:5000"
    depends_on:
      - postgres-products

  order-service:
    build:
      context: ./order-service
    ports:
      - "4000:4000"
    depends_on:
      - postgres-orders

  postgres-users:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"

  postgres-products:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - "5433:5432"

  postgres-orders:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5434:5432"
